var activities = angular.module('activities', [
  // Módulos de angular
  'ngRoute',
  'ui.sortable',

  // Otros
  'directives',
  'factories',

  // Conceptos
  'lizLetter1',
  'lizCompetences',
  'lizText1',
  'lizClickImages',
  'lizImagesAndText',
  'lizMultiplesImagesAndText',
  'lizTwoFramesDescription',
  'lizBoxAnimationFigure',
  'lizImagesInfo',
  'lizClickTransition',
  'lizShowParts',
  'lizWatch',
  'lizTable',
  'lizInputsAndTable',
  'lizShowConcepts',
  'lizHoverShowText',
  'lizShowName',
  'lizShowConceptsText',
  'lizChangeStyleSelect',
  'lizChangeStyleClick',
  'lizShowConceptsCharacter',
  'lizShowConceptsCharacters',
  'lizShowConceptsGroupExamples',
  'lizShowDescriptionImagesSound', // Maria Giraldo
  'lizShowTextCharacter',
  'lizSlideShowCharacter',
  'lizClickImageMap',
  'lizZoom',
  'lizImageMapDescription',
  'lizImageMapMat',
  'lizShowdescription',
  'lizConceptsTable',
  'lizShowImagesBlockDescription',
  'lizImagesBlockDescription',
  'lizImagesBlockMat',
  'lizShowMultipleHoverPhrase',
  'lizCorrectWordInSentence',

  // Actividades
  'lizAnimationBase',
  'lizChooseItems',
  'lizPairs',
  'lizCompleteInputs',
  'lizSelectOptionsImg',
  'lizDropCondition',
  'lizCompleteInputsDescription',
  'lizOneGroup',
  'lizOneGroupToogle', //Maria Giraldo
  'lizOneGroupRule',
  'lizTwoGroup',
  'lizRadioQuestions',
  'lizRadioQuestionsImages',
  'lizSideNumbers',
  'lizOneGroupShape',
  'lizGreaterLowerMat',
  'lizAbacus',
  'lizGiraffe',
  'lizDifferences',
  'lizLetterSoup',
  'lizCrossword',
  'lizCrosswordWithLetter', //Maria Giraldo
  /*'lizCrosswordWithPuzzle', */
  'lizSoundGroup',
  'lizSoundGroups',
  'lizTransclusion',
  'lizTransclusions',
  'lizPairsInputs',
  'lizClickAndListen',
  'lizBuyItems',
  'lizDropOut',
  'lizSelectWords',
  'lizImageMapSelect',
  'lizTangram',
  'lizTablePath',
  'lizReplaceWithInputs',
  'lizReplaceWithInputsMat',
  'lizTablePathInstruction',
  'lizCountElements',
  'lizDropBoxes',
  'lizDragMarkCanvas',
  'lizCountElements',
  'lizCountElements2',
  'lizCompareSample',
  'lizGreaterLowerThan',
  'lizCompleteLetters',
  'lizChalkboard',
  'lizDragToText',
  'lizDragToTexts', 
  'lizDragToImg',
  'lizDragToMat',
  'lizImageGroupDrop',
  'lizCompleteWords',
  'lizGroupCompleteWords',
  'lizGroupCompleteLetters',
  'lizGroupCompleteImages',
  'lizGroupClassifyTable',
  'lizGroupSelectWords',
  'lizClickToSelectPosition',
  'lizClickToCompleteInput',
  'lizCompleteInputsPosition',
  'lizGroupCompleteSound',
  'lizGroupCompleteText',
  'lizGroupTableTextFree',
  'lizGroupTableTextConditions',
  'lizGroupTableTextConditionsOptions',
  'lizGroupTableTextOptions',
  'lizGroupCompleteTextFree',
  'lizGroupCompleteFreeConditions',
  'lizGroupCompleteYesNot',
  'lizGroupCompleteSounds',// No utilizar solo realizando una prueba gregory
  'lizCompleteWordsWi',
  'lizCompleteInputsFree',
  'lizComplementary',
  'lizNumericSequences',
  'lizDragDropMultiples',
  'lizDragDropMultiplesPositions',
  'lizOperationInput',
  'lizDropImageSample',
  'lizThousandNumbers',
  'lizTenThousandNumbers',
  'lizThousandPatterns',
  'lizStackMultiple',
  'lizSequences',
  'lizGroupInputs',
  'lizButtonBubbleDescription',
  'lizPuzzleWord',
  'lizCompareSounds',
  'lizMultipleSelection',
  'lizDragDropMark',
  'lizMultipleMark',
  'lizMultipleImageMapDescription',
  'lizPuzzle1',
  'lizPuzzle2',
  'lizPuzzle3',
  'lizPuzzle4',
  'lizPuzzle5',
  'lizPairsSquares',
  'lizShowConceptsImages',
  'lizShowConceptsImg',
  'lizCompleteTableInputs',
  'lizCompleteTableImageInputs',
  'lizCompleteInputsTrueFalse',
  'lizCompleteTableWithList',
  'lizBubbleDescription',
  'lizCompleteTableWithText',
  'lizChooseCorrectOption',
  'lizClickAndListen',
  'lizImageSound',
  'lizWriteTrueFalse',
  'lizCompleteInputParts',
  'lizCompleteTextBoxes',
  'lizCompleteWordsSelect',
  'lizSelectCheckbox',
  'lizDragDropMultiplesDiff',
  'lizComplementary2',
  "lizTextActivity",
  'lizPairsWithMessage',
  'lizSelectQuestions',
  'lizSelectOptionsPositions',
  'lizChooseCorrectImage',
  'lizSelectTableImageMultiple',
  'lizSelectCorrectImageOption',
  'lizSelectAllCorrectImageOption',
  'lizShowHoverWords',
  'lizJoiningLines',
  'lizGroupSelectMultiplesWords',
  'lizCompleteMultitable',
  'lizSelectOptionsTable',
  'lizCompleteTableRandomInputs',
  'lizCheckboxOptions',
  'lizGroupTableCompleteWords',
  'lizGroupChoiceWords',
  'lizDragDropPairText',
  'lizGroupPuzzleWord',
  'lizQuestionsImages', //Maria Giraldo
  'lizChooseCorrectImageSecuence', //Maria Giraldo

  // Animations
  'lizAnimationVideo'


]);
